# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Install dotnet coverage
      run: dotnet tool install --global dotnet-coverage
      
    - name: Coverage
      run: dotnet-coverage collect dotnet test --no-build -f xml  -o 'coverage.xml'
      
    - name: Install dotnet SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: | 
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:${{ vars.SONAR_PROJ_KEY }} /o:${{ vars.SONAR_ORG_KEY }} /d:sonar.token=$SONAR_TOKEN /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --no-incremental --disable-build-servers
          dotnet sonarscanner end /d:sonar.token=$SONAR_TOKEN
